all: clear rm client server envoi
#test

#remove compile project
rm : 
#	rm client
#	rm server
	rm envoi
#clear console
clear : 
	clear 

client :
	g++ client.cpp -o client 
# 
#-lnsl -lsocket
server : 
	g++ server.cpp -o server 
# 
#-lnsl -lsocket
#
envoi: 
	g++ envoi.cpp -o envoi
#
# test : 
#	g++ test.cpp -o test